name: check_code_quality
on: pull_request # Exécuter lors des pull requests
jobs:
  black:
    runs-on: ubuntu-20.4  # Utilise une machine virtuelle Ubuntu
    steps:
      - uses: actions/checkout@v3  # Récupère le code du dépôt
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Installe Python 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install black  # Installe Black
      - run:
          black --check --verbose .  # Vérifie le formatage du code avec Black
